# Generated by Django 3.0.7 on 2020-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(null=True)),
                ('formattedPrice', models.CharField(max_length=50)),
                ('buyUrl', models.CharField(max_length=200)),
                ('imageUrl', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=200)),
                ('product_type', models.CharField(max_length=200)),
                ('isDeleted', models.BooleanField(default=False, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
