# Generated by Django 3.0.7 on 2020-06-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='metaData',
            field=models.TextField(null=True),
        ),
    ]
